image: golang:1.10-stretch

variables:
    GIT_STRATEGY: clone

before_script:
    - pwd
    - mkdir -p $GOPATH/src/salsa.debian.org/$CI_PROJECT_NAMESPACE
    - cp -r $CI_PROJECT_DIR $GOPATH/src/salsa.debian.org/$CI_PROJECT_PATH
    - cd $GOPATH/src/salsa.debian.org/$CI_PROJECT_PATH
    - pwd

test:
   script:
        - make get-deps
        - make test

pages:
    stage: deploy
    script:
        - make get-deps
        - apt-get update
        - apt-get install -y graphviz
        - mkdir public
        - make dependency-graphs
        - mv dependency-graph-*.svg public/
        - mv public /builds/autodeb-team/autodeb/public
    artifacts:
        paths:
            - public
    only:
        - master
