image: golang:1.10-stretch

before_script:
    - pwd
    - mkdir -p $GOPATH/src/salsa.debian.org/$CI_PROJECT_NAMESPACE
    - cp -r $CI_PROJECT_DIR $GOPATH/src/salsa.debian.org/$CI_PROJECT_PATH
    - cd $GOPATH/src/salsa.debian.org/$CI_PROJECT_PATH
    - pwd

test:
   script:
        - make get-deps
        - make test
